### ISSUE TITLE
Feedback for “参数化：编译时元编程”

### ISSUE THREAD

**Issue by m4p1e** [shadowqcom/mojo_CN#16]
[参数化函数](https://mojocn.org/manual/traitsandparameters/parameterizationcompiletimemetaprogramming#%E5%8F%82%E6%95%B0%E5%8C%96%E5%87%BD%E6%95%B0) 中的第一个例子显示问题, 应为:
```mojo
fn repeat[count: Int](msg: String):
    @unroll
    for i in range(count):
        print(msg)
```
后面的`repeat[3]()`也应为`repeat[3]("Hello")`.

**Comment by shadowqcom** [comment]
已经修复 [参数化函数](https://mojocn.org/manual/traitsandparameters/parameterizationcompiletimemetaprogramming#%E5%8F%82%E6%95%B0%E5%8C%96)
